### ISSUE TITLE
Reference to non-existent field 'sins' Error

### ISSUE THREAD

**Issue by swadhin** [covarep/covarep#103]
When I am running, HOWTO_hmpd.m, I am getting this error. What can be the reason for it ?

**Comment by gillesdegottex** [comment]
I cannot run it right now, may I ask someone to run HOWTO_hmpd from a fresh master version ? (@twoertwein ? @fusaroli ?

**Comment by fusaroli** [comment]
OSX high sierra, Matlab 2017b, fresh master HOWTO_hmpd.m works fine

**Comment by gillesdegottex** [comment]
@swadhin what's your OS and Matlab version ?
Can you try HOWTO_hmpd.m from a fresh master copy ?

**Comment by swadhin** [comment]
With the fresh master copy, it started working. MacOS Sierra and Matlab R2016b. I do not know the reason though. One more related query, how do I create a f0 curve text file for a normal wave file ?

**Comment by twoertwein** [comment]
you can create a CSV file containing the f0 curve with (or by directly calling pitch_shr):
`COVAREP_feature_formant_extraction_perfile(audio_file, struct('features', {{''f0''}}, 'save_csv', 'path_to_csv'))`

**Comment by gillesdegottex** [comment]
The main subject of this issue has been solved, so I close it.
Feel free to continue on this side subject (even though it would be better to open another issue)
