### ISSUE TITLE
Question: Memory-dependent vectorization of pitch_srh 

### ISSUE THREAD

**Issue by twoertwein** [covarep/covarep#105]
would it be worth it detecting the available memory and estimating the expected memory usage to vectorize the fft in pitch_srh (again)?https://github.com/covarep/covarep/blob/4d25cb1e963f9ba4f03c422cede32af9875d7591/glottalsource/pitch_srh.m#L130

If  not enough memory is available, we could have a loop (with a few iterations) over vectoricable blocks which fit into memory. This should (1) be faster than processing every frame individually and (2) it will make it possible to process "really" long audio files with little memory. To achieve (2) the new loop would need to span until this line https://github.com/covarep/covarep/blob/4d25cb1e963f9ba4f03c422cede32af9875d7591/glottalsource/pitch_srh.m#L159 I have audio files which when processed with the current pitch_srh exceed 16GB of memory.

Detecting the available memory is platform-depended but we could use a solution similar to https://www.mathworks.com/matlabcentral/fileexchange/45598-memoryinfo (using matlab's built-in function `memory` on Windows and parse the output of `free` on unix-like OSes).

I could implement that but first wanted to ask whether that would be welcomed (`free` should exist on probably all platforms but there might be cases where it doesn't exist). In cases we cannot estimate the available memory, we could assume that everything fits in the memory (most people process short files). 

Independent of this, there should be a 'else break'-block in following line to avoid a second iteration which does exactly the same: https://github.com/covarep/covarep/blob/4d25cb1e963f9ba4f03c422cede32af9875d7591/glottalsource/pitch_srh.m#L156

**Comment by gillesdegottex** [comment]
(sorry for the late reply, I've just to wrap up some reports these days)

I've the impression such an optimisation goes really outside of the scope of COVAREP.
On the one hand, COVAREP is often used as feature extraction toolbox in many application (as far as I can see from the citations of the paper). In this context, pushing for more optimisation makes fully sense.
On the other hand, COVAREP is first designed to "open" the content of speech algorithms, which means the code should still be readable easily for anybody to understand has been done in the actual code.
With this perspective, pushing for optimisation is scrambling the readability of the code.

This optimisation seems also quite specific (to deal with huge files). Doesn't it make more sense to actually reimplement the code in a faster language ?

You could still make a separated pitch_srh_bigfile.m I would be happy to pull it.

**Comment by twoertwein** [comment]
sorry for the late reply. I agree that it might make the code less readable - let's see, I will be working on 'pitch_srh_bigfile.m' hopefully this week. Other frameworks, such as openSMILE, might be more suitable for realtime applications and long audio files but I would still want to compare features which both have in common (are they actually very similar). For this comparison, I will need to run COVAREP on long files.

**Comment by twoertwein** [comment]
if each frame (or a block of frames) would be processed at a time, the 2nd iteration of pitch track estimation is not possible (`specMat` would not contain the entire data).

I will shortly create two pull request:
1) Add a start/stop option to `COVAREP_feature_formant_extraction_perfile` to only extract features in a specified interval. Many long audio files have 'nothing' in the beginning and end. That helps to easily shorten the audio signal.
2) Re-use variables to allow MATLAB to use in-place operations in `pitch_srh`. Slightly fewer memory allocations need to be done. Unfortunately, it doesn't reduce the peak memory usage of `pitch_srh` (`specMat` is the memory bottleneck).
