### ISSUE TITLE
Example/script how to use it?

### ISSUE THREAD

**Issue by EgorLakomkin** [covarep/covarep#109]
Hi,

Thank you for the library! I would like to use it and I wanted to ask if there is any docs/example on how to use it?

**Comment by gillesdegottex** [comment]
Hey, thanks!

There are many HOWTOs, here:
https://github.com/covarep/covarep/tree/master/howtos

Cheers,

**Comment by EgorLakomkin** [comment]
Many thanks! Somehow I missed it, appreciate your help!
