### ISSUE TITLE
Contributions in python

### ISSUE THREAD

**Issue by sdrobert** [covarep/covarep#111]
Hello,

I would like to contribute to your repository some filter-bank representation code. I have tested it extensively. However, it is written in python. Is it possible to contribute python code somehow?

Best,
Sean

**Comment by gillesdegottex** [comment]
Hi, unfortunately this repo is only for Matlab code.
We wanted to start a parralel repo with Python code, but we always lacked the time to do it.
Thanks for your interest!

**Comment by sdrobert** [comment]
Thanks for getting back to me. An awkward question, but one I'd hope you'd answer for the sake of reproducible results: any other open-source speech-community-driven projects you know of that work in C++ or Python? Thanks!

**Comment by gillesdegottex** [comment]
I would say you can find projects of both languages. E.g. SPTK in C, and most DNN-related work in Python.
