### ISSUE TITLE
Octave: Error in loading system_net_creak

### ISSUE THREAD

**Issue by JoFrhwld** [covarep/covarep#29]
When loading `system_net_creak` in octave, the following errors pop up:

    warning: load: can't find the file C:\Program Files\MATLAB\R2011a\toolbox\nnet\nnet\nnweight\dotprod.m
    warning: skipping over ''
    warning: load: can't find the file C:\Program Files\MATLAB\R2011a\toolbox\nnet\nnet\nnweight\dotprod.m
    warning: skipping over ''
    warning: load: can't find the file C:\Program Files\MATLAB\R2011a\toolbox\nnet\nnet\nnweight\dotprod.m
    warning: skipping over ''
    warning: load: can't find the file C:\Program Files\MATLAB\R2011a\toolbox\nnet\nnet\nnnetinput\netsum.m
    warning: skipping over ''
    warning: load: can't find the file C:\Program Files\MATLAB\R2011a\toolbox\nnet\nnet\nnnetinput\netsum.m
    warning: skipping over ''
    warning: load: can't find the file C:\Program Files\MATLAB\R2011a\toolbox\nnet\nnet\nntransfer\tansig.m
    warning: skipping over ''
    warning: load: can't find the file C:\Program Files\MATLAB\R2011a\toolbox\nnet\nnet\nntransfer\logsig.m
    warning: skipping over ''
    warning: load: can't find the file C:\Program Files\MATLAB\R2011a\toolbox\nnet\nnet\nntransfer\tansig.m
    warning: skipping over ''
    warning: load: can't find the file C:\Program Files\MATLAB\R2011a\toolbox\nnet\nnet\nntransfer\logsig.m
    warning: skipping over ''
    warning: no constructor for class network
    warning: load: element has been converted to a structure

Since `system_net_creak` isn't successfully loaded, `creaky_voice_do_detection` fails at line 87

    > creak_pp=sim(net,X);
    error: Structure doesn't seem to be a neural network

**Comment by gillesdegottex** [comment]
I'm closing this issue since it is inactive for a year.

We can re-open it anyway if someone find an Octave-compatible ANN toolbox.
detect_creaky_voice.m will stay Octave incompatible until then.
