### ISSUE TITLE
Index exceeds matrix dimensions. Error in spec_getsins_f0 (line 61)

### ISSUE THREAD

**Issue by StevenLOL** [covarep/covarep#51]
In this function. line 61. the k could be a 1x1 double, then Index exceeds matrix dimensions.

function sins = spec_getsins_f0(S, fs, f0, max_h)

    % ... and replace by the peaks found.
    [k, v] = v_findpeaks(abs(S(1:end/2+1)), 'q');
    D = abs(repmat(k,1,max_h)-repmat(1+sins(1,:), length(k),1));
    [mind, mindi] = min(D);
    idx = mind<step/2;
    sins(1,idx) = k(mindi(idx))-1;

**Comment by StevenLOL** [comment]
This happens only when apply following setting, normally in the last few frames of the audio data. In my data base, 6/16000 audio have such problem.  

    hmpdopt = hmpd_analysis();
    hmpdopt.f0min   = 75; % To adapt to the analyzed voice
    hmpdopt.f0max   = 220;% To adapt to the analyzed voice
    %Speed up options
      hmpdopt.sin.use_ls=false;   % For analysis step, use simple Peak Picking 
      hmpdopt.sin.fadapted=false; % For analysis step, use the stationary DFT 
      hmpdopt.usemex = true; % Use mex linear interp (affects mainly the synth.)


There will be no such error if set following to true:
      hmpdopt.sin.use_ls=true;   % For analysis step, use simple Peak Picking 
      hmpdopt.sin.fadapted=true; % For analysis step, use the stationary DFT

**Comment by gillesdegottex** [comment]
Hello, thanks for the feedback!
Could you send me one of the audio file which causes this specific problem ?
I'll fix this asap.

**Comment by StevenLOL** [comment]
I have one file [here](https://www.dropbox.com/s/4zbc3y0zcyrk219/temp03.wav?dl=0)

**Comment by gillesdegottex** [comment]
I committed a fix (and a few others in the meantime).
Could you try the master version and tell me if it works on the 6 remaining files ?
Thanks

**Comment by StevenLOL** [comment]
Still have (two)[https://www.dropbox.com/sh/ih2xrb6xg1s54d0/AACyT7Wo4PFMGJzaa39g_3sYa?dl=0]  left, seems another type of error.

**Comment by gillesdegottex** [comment]
The first one had no voiced segment detected, f0max is set to low apparently, f0 reaches 300Hz at some point.
The second one had a single frame detected as voiced.

Fix and warning commited in 329cd71ef4a87693f55626f411bfcb0567cd84d9.

**Comment by gillesdegottex** [comment]
Tell me if everything's fine on your side please, when you have a moment.

**Comment by StevenLOL** [comment]
Thanks, no more problems.
