### ISSUE TITLE
wavread and wavwrite are not valid functions in Matlab 2015b

### ISSUE THREAD

**Issue by fusaroli** [covarep/covarep#59]
Wavread can be replaced with audioread, with no other changes 
Wavwrite can be replaced with audiowrite, but the input syntax is slightly different: the filename has to be put first (now it’s the third input).

In order to keep back-compatibility, you could use a try (old function) and catch (new function) solution. This seems to work on both my Matlab 2012a and Matlab 2015b.

**Comment by gillesdegottex** [comment]
Hello Riccardo!
Sorry for the "summer" delay.
I made the replacements and used backward compatibility functions in the external directory.
Thanks,
Cheers

**Comment by howon52** [comment]
@gillesdegottex Hello, experiencing similar error in matlab 2017a ([https://github.com/covarep/covarep/issues/91](url)). Am I missing something blatantly obvious, such as copying the files in the external/backcompatibility_2015 directory to somewhere else?

**Comment by gillesdegottex** [comment]
the path external/backcompatibility_2015 might have end up in your path directory.
the startup/m script is suposed to remove it from your paths depending on the Matlab version.

Try remove it from your path.
