### ISSUE TITLE
Glottal source crash (Matlab 2015b?)

### ISSUE THREAD

**Issue by fusaroli** [covarep/covarep#68]
I have been trying to apply the glottal source how-to to one of my files (https://www.dropbox.com/s/00dqqrs56jkq2nr/sc1_1.wav?dl=0) on Matlab 2015b (OS X, Yosemite), but I get several issues.

1. the script tries to rely on the backcompatibility version of audioread, which crashes. I had to delete the backcompatibility version.

2. the creaky voice detection says "Version or toolboxes do not support neural network object used in creaky voice detection. Creaky detection skipped."
The within function errors are:

Error using xcorr>parse_maxlag (line 356)
Maximum lag MAXLAG must be an integer.

Error in xcorr>parseinput (line 308)
maxlag = parse_maxlag(maxlag,m);

Error in xcorr (line 63)
[xIsMatrix,autoFlag,maxlag,scaleType] = parseinput(x,varargin{:});

Error in get_ifp (line 75)
    [ACF,lags]=xcorr(frame,maxLag,'coeff'); % get normalised autocorrelation function

Error in ishi_creak_detection (line 146)
[IFP,t_IFP,IFP_peaks] = get_ifp(x_filt,fs,IFPthresh,t_pow,peak_idx);

Error in get_ishi_params_inter (line 79)
[dec_orig,t_IFP,IFP_cur,PwP_cur,IPS_cur,t_pow] = ishi_creak_detection(x,fs,0);

Error in get_all_creak_features (line 57)
[PwP,IFP,IPS] = get_ishi_params_inter(x,fs);

Error in detect_creaky_voice (line 75)
FeatMat = get_all_creak_features(x,fs);

3. the subsequent functions fail. Here the errors:

Error using zeros
Size inputs must be integers.

Error in lpcresidual (line 53)
LPCcoeff=zeros(order+1,round(length(x)/shift));

Error in se_vq (line 77)
res = lpcresidual(x,winLen/1000*fs,winShift/1000*fs,LPC_ord); % Get LP residual

Error in HOWTO_glottalsource (line 59)
se_gci = se_vq(x,fs,median(srh_f0),creak);           % SE-VQ

**Comment by gillesdegottex** [comment]
Hello, thanks for all this feedback !

For 1. there is a startup script at the root of the repository. It should automatically remove the backcompatibility folder for your Matlab 2015.

For 2. It seems necessary to have a specific version of Matlab for loading the neural nets weights. That's an issue indeed. @ThomasDrugman is there a way to save and load the weights using text files ? Or any other binary file which is independent on the Matlab version?

I commited 2 fix for the functions which were crashing. Please tell me it goes through now.
(the fs was assumed to be multiple integer of 1000, and I assume you were using 22050 or 11025Hz sampling).

Cheers,

**Comment by fusaroli** [comment]
Thanks for the help! Yes, I have a couple of papers under review advocating exactly this kind of collaborative code repositories (for the analysis of voice in right hemisphere damage patients and in autism), so I am trying to be consistent (though it means re-running a whole set of analyses, and spamming the issues forum :-) ).

1. Startup: I tried it, but it does not delete the folder... Additionally it gives two warnings:
> Function plot3 has the same name as a MATLAB builtin. 
> Function assert has the same name as a MATLAB builtin. 

2. Thanks. Looking forward to a solution

3. Yes, my audios are all 44100 Hz. Now "se_vq" works fine, but the previous function "gci_sedreams" crashes. Might it be still the sampling frequency, since fs is involved? Here the errors:

> In an assignment  A(:) = B, the number of elements in A and B must be the same.
>
> Error in gci_sedreams (line 174)
>            gci(Ind)=start+posi-1;
>
> Error in HOWTO_glottalsource (line 58)
> sd_gci = gci_sedreams(x,fs,median(srh_f0),1);        % SEDREAMS

Everything else not relying on sd_gci works fine.

Also (of minimal concern) an additional warning of "obsolete" function properties:
> The EraseMode property is no longer supported and will error in a future release.
> Use the ANIMATEDLINE function for animating lines and points instead of EraseMode 'none'.
> Removing instances of EraseMode set to 'normal', 'xor', and 'background' has minimal impact.

**Comment by gillesdegottex** [comment]
1. I pushed a fix for the startup, it should be a bit more robust. Also, it is not supposed to delete the files, but just remove the access path to the Matlab path variable, which should be enough.

3. I pushed a fix but could you send me the wav file for which it crashes ? Because I would like to double check this.

I cannot find any statement of EraseMode in COVAREP, are you sure it's not from another piece of code ? Same for definitions of plot3 and assert, cannot find such things in COVAREP.

**Comment by fusaroli** [comment]
1. Now it works

2. Still issues here with gci_sedreams.m:
> Index exceeds matrix dimensions.
>  Error in gci_sedreams (line 174)
>            gci(Ind)=start+posi(1)-1;
> Error in HOWTO_glottalsource (line 58)
> sd_gci = gci_sedreams(x,fs,median(srh_f0),1);        % SEDREAMS

It seems that at a certain point interv=Maxis(k)-Minis(k) (line 157) gives a negative result, so that when on line 172 it tries to define:
> vec=res(start:stop);
it generates an empty vector, with all the ensuing issues.

3. after following on plot3, assert and eraseMode, it seems they are internal issues to Matlab2015b. In other words, they are called in by built-in functions (matlabpath.m and waitbar.m), so not much to do there.

**Comment by gillesdegottex** [comment]
Your sound works flawlessly on my machine using the command:
>> [gci, MeanBasedSignal, res] = gci_sedreams(wav, fs, 162, 1);

Can you tell me which command are you using and which sound (if different from above) ?

**Comment by gillesdegottex** [comment]
Closing this one in favor to #71 to address the specific issue of loading the neural net weights.
