### ISSUE TITLE
How-to Spectra "Interpolation requires at least two sample points in each dimension."

### ISSUE THREAD

**Issue by fusaroli** [covarep/covarep#70]
Same file and system: (https://www.dropbox.com/s/00dqqrs56jkq2nr/sc1_1.wav?dl=0) on Matlab 2015b (OS X, Yosemite).

> Error in interp1 (line 161)
>        F = griddedInterpolant(X,V,method);
> Error in fchtgram (line 70)
>    f0 = interp1(f0s(:,1), f0s(:,2), T, 'linear','extrap');
> Error in HOWTO_spectra (line 48)
> [FC, freqs, ts, as] = fchtgram(wav, win, winlen-hopsize, dftlen, fs, f0s);

**Comment by gillesdegottex** [comment]
Same as for the other howtos, can you try the two lines I indicated in #69 ?

**Comment by fusaroli** [comment]
Solved. I had tried just using the srh_f0(:) as f0s. My bad.
Thanks again
