### ISSUE TITLE
Neural net definitions for creaky voice detection are very specific to the used Matlab version. It seems that Matlab2015 cannot load them anymore.

### ISSUE THREAD

**Issue by gillesdegottex** [covarep/covarep#71]
From #68:
- The creaky voice detection says "Version or toolboxes do not support neural network object used in creaky voice detection. Creaky detection skipped."

- It seems necessary to have a specific version of Matlab for loading the neural nets weights. That's an issue indeed. @ThomasDrugman is there a way to save and load the weights using text files ? Or any other binary file which is independent on the Matlab version?

**Comment by fusaroli** [comment]
This now works in the latest release of Matlab 2015b.

**Comment by gillesdegottex** [comment]
You mean it was not working with Matlab 2015a but it works with Matlab 2015b ?

**Comment by fusaroli** [comment]
I had a test pre-release of Matlab 2015b, which crashed the creaky detection. I now installed the actual release and the problem disappeared.

**Comment by gillesdegottex** [comment]
Awesome, thanks for the good news :+1:
