### ISSUE TITLE
Phase (un)wrapping artifacts in HMPD vocoder

### ISSUE THREAD

**Issue by Sleepwalking** [covarep/covarep#74]
Hello all,

At [`hmpd_phase_decompress.m`, line 61](https://github.com/covarep/covarep/blob/master/vocoder/hmpd/private/hmpd_phase_decompress.m#L61), Phase Distortion Mean is unwrapped, followed by an interpolation. Here's a pitfall we forgot to deal with: phase unwrapping may be inconsistent across frames. It's better to illustrate this problem by giving an example:

At frame n-1, we have two neighbouring harmonics whose wrapped PDMs are
```
[0.3pi, -0.8pi]
```
So the unwrapped PDMs for frame n-1 are
```
[0.3pi,  1.2pi]
```

At frame n, let's say the PDM for the second harmonic becomes 0.2pi higher,
```
[0.3pi, -0.6pi]
```
However this time phase unwrapping gives utterly different result:
```
[0.3pi, -0.6pi]
```

Without pitch shifting/interpolation this inconsistency doesn't matter. But if we interpolate right in the middle, the result will be (0.3pi + 1.2pi)/2 = 0.75pi and (0.3pi - 0.6pi)/2 = -0.15pi respectively - we get almost 180 degree phase shift across two frames! If you play the pitch-shifted sound you may hear occasional 'clicks' in voiced speech.

Since PDM is calculated in a manner similar to group delay, an error in the n-th harmonic will affect all harmonics above it (n,n+1,n+2,...N).

Surprisingly the samples under `howtos` directory have very few artifacts (probably because these samples have relatively low f0 so the phase response is densely sampled, and hence PDM is closer to zero). But I do observe some severe artifacts in a singing voice corpus, when down-scaling the pitch by half:

![screenshot from 2015-11-15 11 40 53](https://cloud.githubusercontent.com/assets/4531595/11170028/cca2ab08-8b8d-11e5-93bf-f05b73ee31a4.png)
(clicks occur at 3.05s, 3.60s, 3.70s and 3.95s)

A wav file from the corpus is attached here,
https://mega.nz/#!SI4hFRKA!ppTC-t8qXjt5sKa0cxT9tYXbivHU1DWl5O_YJJ58TBA
To give credit: this corpus ("Yamine Renri 1.0") was recorded for UTAU, a Japanese concatenative singing voice synthesis software. The website for this corpus is [here](http://renri-voice.com/index.html) (free for download). I'm neither the author of the corpus nor the author of UTAU.

Dr. Jordi Bonada at Music Technology Group had pointed out a very similar problem in a 2004 paper and he offered a solution in section 3.2:
> Bonada, Jordi. "High quality voice transformations based on modeling radiated voice pulses in frequency domain." Proc. Digital Audio Effects (DAFx). 2004.

I implemented his method. Clicks are gone, but it sounds a little bit blurred as a side effect. Anyone has better idea on solving this problem?

Regards,
Kanru Hua

**Comment by Sleepwalking** [comment]
Note: [`phase_rpspd`](https://github.com/covarep/covarep/blob/master/envelope/phase_rpspd.m#L183) is also vulnerable to unwrapping discontinuities.

**Comment by gillesdegottex** [comment]
At hmpd_phase_decompress.m, line 61, the unwrapping/interpolation is across harmonics, not frames.

Anyway, basically, yes, there is always phase unwrapping issues.

If you resample the PDM where it was measured, it will be unlikely to have any artifact (it is not impossible that the averaging effect in the PDM computation might actually create some errors).
If you resample the PDM at different points (e.g. during pitch shifting), you will end up with the usual phase interpolation issues, like in any vocoding technique.

It's great if you've found a better interpolation method.
I think @ThomasDrugman has another solution here:
https://github.com/covarep/covarep/blob/master/spectrum/drugmanunwrapping.m

**Comment by Sleepwalking** [comment]
Thanks for your reply!
It seems like Drugman's unwrapping works on narrowband spectrum. Does it also unwraps harmonic phases or I should first use it on STFT phase spectrum and then pick the peaks?

**Comment by gillesdegottex** [comment]
Better to ask him @ThomasDrugman  directly ;)

**Comment by ThomasDrugman** [comment]
Hi,

I am missing the context of the question.
What I can tell you is that there is absolutely no assumption (about e.g. the nature of the signal, its harmonics or whether it is wideband or not) made by this algorithm:
http://tcts.fpms.ac.be/~drugman/files/IS15_PhaseUnwrap.pdf

It takes a wrapped phase as input, and unwraps it.

If this does not clarify your doubts, could you please give me the context of your question?

Thanks,

Thomas



De : Kanru Hua [mailto:notifications@github.com]
Envoyé : lundi 30 novembre 2015 23:45
À : covarep/covarep
Cc : Thomas DRUGMAN [530408]
Objet : Re: [covarep] Phase (un)wrapping artifacts in HMPD vocoder (#74)


Thanks for your reply!
It seems like Drugman's unwrapping works on narrowband spectrum. Does it also unwraps harmonic phases or I should first use it on STFT phase spectrum and then pick the peaks?

**Comment by Sleepwalking** [comment]
Hello Dr. Drugman,

Thanks for your clarification. We are unwrapping the phases of harmonics (in a frame) for a harmonic model. My concern is that the spectrum is too sparsely sampled (only at harmonics) that recovering the unwrapped phase is very difficult.
I've tried to replace `unwrap` by `drugmanunwrapping` but there are still artifacts (though fewer) and I see lots of "convergence not reached after 12 iterations".

By the way, at [line 74, `drugmanunwrapping.m`](https://github.com/covarep/covarep/blob/master/spectrum/drugmanunwrapping.m#L74) there's a typo. `angl` should be `angle`.

Regards,
Kanru Hua

**Comment by gillesdegottex** [comment]
Since this issue is related to a general research problem (phase unwrapping) and not a COVAREP-specific issue, I'm closing it.

Thanks for spoting the typo/bug!
