### ISSUE TITLE
VAD_Drugman_FeatureExtraction generating NaNs

### ISSUE THREAD

**Issue by fusaroli** [covarep/covarep#75]
I am having issues on using VAD_Drugman_FeatureExtraction.m as for some audiofiles it generates NaNs for all the outputs.

Example of file generating only NaNs: https://www.dropbox.com/s/grgxdpm385kgbrw/TomalASD113A.wav?dl=0
Example of file with analogous features, but generating meaningful output: https://www.dropbox.com/s/u5k36yq21wy2q4u/TomalASD115A.wav?dl=0

I am using the latest 1.4.1 version of Covarep on Matlab 2015b.

**Comment by ThomasDrugman** [comment]
Hi,

Sorry for the delay, I am pretty busy these days.
Thanks for reporting this bug. Unfortunately the pointers to the files are dead. Any chance that you share this file again?
Are you still meeting this issue? Have you noticed any pattern why it would be failing for certain files?

Thanks,

Thomas

**Comment by fusaroli** [comment]
Sorry, new links:
- non-working file: https://www.dropbox.com/s/eh5hmea4zlhzj74/TomalASD113A%20.wav?dl=0
- working file: https://www.dropbox.com/s/946bfx9q0i62wnx/TomalASD115A.wav?dl=0

I was not able to find a clear pattern in the working and non-working files, unfortunately.
Thanks,
R

**Comment by ThomasDrugman** [comment]
Hi Riccardo,

How heavy are these files?
It looks like it is downloading for ever, but never completes.
How about sending them by email to: thomas(dot)drugman@umons.ac.be?

My first guess would be that it is linked to digital silences (only 0s for a period longer than the analysis frame - probably at the beginning of the file). Did you check that?

Te ringrazio!

**Comment by fusaroli** [comment]
As far as I can assess all problematic files start with voice, so that should not be the issue.
I sent you the 2 ca 6MB files by mail.
Grazie mille!

**Comment by ThomasDrugman** [comment]
I checked the files you have sent me: the problematic file starts with about 90ms of digital silence. The one for which it works "only" has about 35 ms of digital silence.
As I mentioned above, my 20 cents are on these digital silences creating issues and generating NaN values from the beginning.

How can we overcome that? A simple way consists in adding a random noise at a very low amplitude (something like 1e-16*rand(1,N)) to the initial waveform.

Gilles: this is a general problem which could possibly affect a few of our analysis techniques. How about adding this tiny noise in the main script at the very beginning prior to any analysis?

Riccardo: would it be possible for you to check that this would solve your issue?

Thanks,

Thomas

**Comment by schererstefan** [comment]
I would suggest using: eps*rand(1,N) instead. This will give you the smallest possible number.

I have a question about this though: Why would we not want to remove/ignore leading zeros?

**Comment by ThomasDrugman** [comment]
Right, eps makes more sense indeed.
The main reasons why not discarding these zeros is that you might want to be in sync in other types of feature extractors or analysis tools.

**Comment by schererstefan** [comment]
right, very good point. Sometimes we actually also want to synchronize with video etc.

**Comment by gillesdegottex** [comment]
Well the zeros ...
I don't like the idea of adding noise systematically prior to any analysis because sometimes we want to evaluate methods with synthetic signals (just to check that the method is working as expected).

Ideally, each analysis method should deal with this case with a dedicated solution (e.g. for f0 estimator, check for energy in the window and return 0 if energy=0).

Though I agree that for some estimators (VAD? feature extraction?), the dedicated solution might to add noise.

One solution might be to create a common function that replace zeros with noise, using eps*rand(1,N). Then we call this function at the beginning of some functions (e.g. the feature extraction script surely and VAD if you think it makes sense, Tom)

**Comment by fusaroli** [comment]
eps*rand(1,N) solves the problem. Thanks!

**Comment by gillesdegottex** [comment]
New utility function: misc/replacezeros.m
Use at will. @ThomasDrugman , @schererstefan, Please use it in the scripts you think it makes sense.
