### ISSUE TITLE
rd_msp throws error due to leading empty entries in frames variable produced by sin_analysis

### ISSUE THREAD

**Issue by schererstefan** [covarep/covarep#77]
Problem is that removing leading empty entries will ultimately alter the length of output from rd_msp. I did make a workaround for my private version of covarep and wanted to see what people think. I basically take the first valid entry from frames variable and duplicate it for the empty ones. This way both rd_msp generates a meaningful output (e.g., the frametime in frames variable is also set to the first valid entry) and doesn't break. 

Here is the workaround to be run between sin_analysis and rd_msp:

```
frames = sin_analysis(audio_samples, fs, [srh_time(:),srh_f0(:)], opt);
% find first valid entry:
counter_for_empty_frames = 1;
while(isempty(frames(counter_for_empty_frames).t))
     counter_for_empty_frames = counter_for_empty_frames + 1;
end
% replace non-valid entries with first valid entry
frames_temp = frames(counter_for_empty_frames);
for fill_frames = 1:counter_for_empty_frames
     frames(fill_frames) = frames_temp;
end

rds = rd_msp(frames, fs);
```

**Comment by gillesdegottex** [comment]
Ouch, my bad. I didn't think of this.
I'll make a "sinusoidal interpolation" function based on your code to fill possible gaps.
And modify rd_msp for returning some meaningful values for empty frames.
Ok?

**Comment by schererstefan** [comment]
sounds good.

**Comment by gillesdegottex** [comment]
Hey, I'm looking at the code, but I don't get how it's possible to have an empty 'frame.t'
Either opt.win_dropoutside==true and and the some 't' are dropped, either they are all kept.

Do you have a problematic wav (and its f0 maybe) ?

**Comment by gillesdegottex** [comment]
Any news about this @schererstefan ?

**Comment by schererstefan** [comment]
I am not quite sure why I got the leading empty frames. My files are in general pretty long and can be quite messy (e.g., no one speaks for a few seconds or you hear some background noise).

**Comment by gillesdegottex** [comment]
sin_analysis and rd_msp are not dependent on a voicing/speech activity, they will both compute something, whatever the underlying signal.

Anyway, since we don't have an example to track this and I really can't find a scenario where this is possible, I'll close this issue. Feel free to re-open it if you find a wavform that leads to such an issue.
