### ISSUE TITLE
Index exceeds matrix dimensions

### ISSUE THREAD

**Issue by bobchennan** [covarep/covarep#81]
Sinusoidal Analysis
      win_durf0sync: 1
       win_durnbper: 3
            win_dur: 0.0300
             win_fn: @blackman
    win_dropoutside: 1
          fharmonic: 0
         fquasiharm: 0
           fadapted: 0
             use_ls: 0
        win_ls_marg: 0.1000
            normstr: 'sum(win)'
             dftlen: 4096
                osf: 2
    frames_keepspec: 1
            funique: 1
              resyn: 0
              debug: 1
             fmapin: {{1x2 cell}  {1x2 cell}}
            fmapout: {{1x2 cell}}

100%   elapsed: 0:0
??? Index exceeds matrix dimensions.

Error in ==> env_interp at 79
        fks = [-fks(5:-1:2) fks];

Error in ==> phase_rpspd at 133
            E = env_interp(frames(n).sins(:,2:end), fs, opt.dftlen, true, 'linear');

Error in ==> RPSPD at 25
    PD = phase_rpspd(frames, fs, opt);

[T1_1008828.zip](https://github.com/covarep/covarep/files/318096/T1_1008828.zip)

**Comment by gillesdegottex** [comment]
Runs smoothly on my side.
There have been changes on how sin_analysis deals with the windows outside signal that was leading to empty frames.
Can you check out the master version ?

**Comment by bobchennan** [comment]
Sure. I cloned it several hours ago(git clone
https://github.com/covarep/covarep)

And sorry this is my code:

```matlab
    [wav, fs] = audioread(wavf);
    [srh_f0,srh_vuv,srh_vuvc,srh_time] = pitch_srh(wav,fs,70,500,10);
    f0s = [srh_time(:), srh_f0(:)];
    dftlen = 4096;
    opt = sin_analysis();
    opt.fharmonic  = false; % Use sinusoidal model (no constrains on the
frequencies)
    opt.use_ls     = false; % Use Peak Picking
    opt.dftlen     = dftlen;  % Force the DFT length
    opt.frames_keepspec = true; % Keep the computed spectra in the frames
structure
    frames = sin_analysis(wav, fs, f0s, opt);
    try
        opt = phase_rpspd();
        opt.harm2freq = true;
        opt.pd_method = 1;
        PD = phase_rpspd(frames, fs, opt);
        opt.pd_method = 2;
        opt.pd_vtf_rm = false;
        opt.polarity_inv = true;
        RPS = phase_rpspd(frames, fs, opt);
        RPSPD = [RPS PD];
        save(savf,'RPSPD');
    catch ME
        fprintf(errs,'%s\n',wavf);
    end
 ```

2016-06-16 18:17 GMT+08:00 Gilles Degottex <notifications@github.com>:

**Comment by bobchennan** [comment]
Sorry. I see the new commit. Let me try it.

**Comment by bobchennan** [comment]
I still meet the same error.

Currently I am extracting Phase Distortion (PD) and the Relative Phase Shift features on a large dataset. I can provider more samples with running error after it is completed.

**Comment by gillesdegottex** [comment]
RPS and PD are computed from harmonic parameters.
Thus, you need to use:
opt.fharmonic  = true;

**Comment by bobchennan** [comment]
Sorry but it isn't used in the HOWTO_envelope.m example.

I still meet the same question. Is there any other parameters which should I change?

**Comment by gillesdegottex** [comment]
Sorry for the confusion in the HOWTO, but apparently it was luckily working with the used sample whereas it shoudn't have.

Youre code works fine on my side if I only change this. Is it okay on your side ?

**Comment by bobchennan** [comment]
Thanks for your help.

Now it solved. I may need several hours further to see if there exists other problems.

**Comment by gillesdegottex** [comment]
Just re-open this issue if you see similar errors or feel free to open a new one.
