### ISSUE TITLE
Program stucked during phase_rpspd

### ISSUE THREAD

**Issue by bobchennan** [covarep/covarep#82]
Output:
    
    Warning: The median frequency difference between sinusoidal components is smaller than 1Hz.         Something is surely wrong in the sinusoidal parameters.
    > In env_interp at 64
    In phase_rpspd at 133
    In RPSPD at 26

Code:
```
    [wav, fs] = audioread(wavf);
    [srh_f0,srh_vuv,srh_vuvc,srh_time] = pitch_srh(wav,fs,70,500,10);
    f0s = [srh_time(:), srh_f0(:)];
    dftlen = 4096;
    try
        opt = sin_analysis();
        opt.fharmonic  = true; % Use harmonic model
        opt.use_ls     = false; % Use Peak Picking
        frames = sin_analysis(wav, fs, f0s, opt);
        opt = phase_rpspd();
        opt.harm2freq = true;
        opt.pd_method = 1;
        PD = phase_rpspd(frames, fs, opt);
```

Running Sample:
[T1_1009041.zip](https://github.com/covarep/covarep/files/318446/T1_1009041.zip)

**Comment by gillesdegottex** [comment]
You've met a bug.
I fixed it on the git.
