### ISSUE TITLE
Some Question about the Glottal Flow Parameter

### ISSUE THREAD

**Issue by nasWang** [covarep/covarep#83]
My project is Speaker Recognition. I want to know how can I use the covarep toolkit extract the feature in the paper "A four-parameter model of Glottal Flow" or "Modeling of the Glottal Flow Derivative Waveform with Application to Speaker Identification"???
Thank you ! ! !

**Comment by gillesdegottex** [comment]
You can have a look at the section Glottal source analysis at:
http://covarep.github.io/covarep/contributions.html

There is currently no available method in COVAREP to estimate all LF parameters independently.
However, rd_msp.m can help you to estimate a meta parameter Rd.

By the way, I'm not sure voice quality might be very useful for ASR.

**Comment by nasWang** [comment]
Thank you !!!
I will learn the way rd_msp.m estimate a meta parameter.
