### ISSUE TITLE
COVAREP_feature_extraction() --> IAIF - frame not analysed!!

### ISSUE THREAD

**Issue by michellemorales** [covarep/covarep#87]
When I run the COVAREP_feature_extraction function in matlab I am receiving this error as output "IAIF - frame not analysed!!" Below is my output, any idea what is going on?

```
>> COVAREP_feature_extraction('/Users/morales/GitHub/Dissertation/')
Analysing file: FerrisBuellerClip
IAIF - frame not analysed!!
IAIF - frame not analysed!!
100%   elapsed: 0:34                       
FerrisBuellerClip successfully analysed```

**Comment by gillesdegottex** [comment]
It is part of the IAIF implementation:
https://github.com/covarep/covarep/blob/0f54f6e280a77dd799bae3e327e7e43e9876af5c/glottalsource/iaif.m

It seems the lpc order for the vocal tract is longer than the signal to analyse.
