### ISSUE TITLE
Get a lot of NAN using VAD_Drugman_FeatureExtraction.m	

### ISSUE THREAD

**Issue by bobchennan** [covarep/covarep#88]
I am going to extract features using VAD_Drugman_FeatureExtraction.m. 

And this is the audio which given NAN results:
[T_1000948.wav.zip](https://github.com/covarep/covarep/files/739668/T_1000948.wav.zip)

**Comment by gillesdegottex** [comment]
Still facing this issue?
Solved?
Gave up?

**Comment by bobchennan** [comment]
Sry I already forgot that. Let me close the issue.
