### ISSUE TITLE
audioread/wavread compatibility

### ISSUE THREAD

**Issue by howon52** [covarep/covarep#91]

**Comment by howon52** [comment]
Here is what I have atm:

**Comment by howon52** [comment]
I am running startup & HOWTO_all on matlab version 2017a, and have run into issues with wavread as below. I though this may be a duplicate issue, but looking at the post [https://github.com/covarep/covarep/issues/59](url), a similar issue on matlab version 2015b, The thread seemed to suggest that the issue was fixed by the folder external\backcompatibility_2015, but I get the following. Am I doing something wrong?

```
>> startup
>> HOWTO_all
Short Time Fourier Transform (DFT based)
Short Time Fan-Chirp Transform (FChT based)
100%   elapsed: 2:8                       
Warning: linkaxes is not implemented in Octave 
> In linkaxes (line 2)
  In HOWTO_spectra (line 69)
  In HOWTO_all (line 3) 
Undefined function or variable 'wavread'.

Error in HOWTO_features (line 13)
[speech, fs]  = wavread(file_name);

Error in HOWTO_all (line 4)
HOWTO_features;
```

**Comment by gillesdegottex** [comment]
You have to add the external/backcompatibility_2015 path in your paths.
(conversely to what I said in the other thread that I'm closing in favor of this one)

**Comment by howon52** [comment]
Thank you for the swift reply.
Ah I see. So it is supposed to be removed from file path normally, but should be included in the 2015+ versions? Seeing from the way it unhighlights itself after running startup.m, I suppose I have to manually add the directory to the paths. 

Doing so, however, did not seem to solve the problem - still same errors regarding wavread. 

So I manually tried manually replacing the wavread with audioread as per the suggestion from the other thread (there were only 2 replacements to make, one in `howtos\HOWTO_features.m` line 13; one in `feature_extraction\modified_group_delay_feature.m` line 31), and it did solve the problem (so I guess there was not much need for this thread other than highlighting that the backcompatibility_2015 does not seem to work on 2017a? - sorry about that) 

It did throw some warning messages though, regarding Octave implementation and some .m file not being able to be cleared. 

Thank you for your help and comment.

If anyone is interested, I get the following:
`
Short Time Fourier Transform (DFT based)
Short Time Fan-Chirp Transform (FChT based)
100%   elapsed: 2:8                       
Warning: linkaxes is not implemented in Octave 
> In linkaxes (line 2)
  In HOWTO_spectra (line 69)
  In HOWTO_all (line 3) 
Warning: linkaxes is not implemented in Octave 
> In linkaxes (line 2)
  In HOWTO_features (line 34)
  In HOWTO_all (line 4) 
Compute: Sinusoidal Model (SM) using Peak Picking
Sinusoidal Analysis
      win_durf0sync: 1
       win_durnbper: 3
            win_dur: 0.0300
             win_fn: @blackman
    win_dropoutside: 1
          fharmonic: 0
         fquasiharm: 0
           fadapted: 0
             use_ls: 0
        win_ls_marg: 0.1000
            normstr: 'sum(win)'
             dftlen: []
                osf: 2
    frames_keepspec: 0
            funique: 1
              resyn: 1
              debug: 1
             fmapin: {{1×2 cell}  {1×2 cell}}
            fmapout: {{1×2 cell}}

100%   elapsed: 0:1                       
    Some windows were outside of the signal. 5 frames dropped. (use opt.win_dropoutside=false if you want to keep all windows and zero-pad the necessary ones at signal boundaries).
Mean SNR=5.6825
Compute: Harmonic Model (HM)
Sinusoidal Analysis
      win_durf0sync: 1
       win_durnbper: 3
            win_dur: 0.0300
             win_fn: @blackman
    win_dropoutside: 1
          fharmonic: 1
         fquasiharm: 0
           fadapted: 0
             use_ls: 1
        win_ls_marg: 0.1000
            normstr: 'sum(win)'
             dftlen: []
                osf: 2
    frames_keepspec: 0
            funique: 1
              resyn: 0
              debug: 1
             fmapin: {{1×2 cell}  {1×2 cell}}
            fmapout: {{1×2 cell}}

100%   elapsed: 0:8                       
    Some windows were outside of the signal. 5 frames dropped. (use opt.win_dropoutside=false if you want to keep all windows and zero-pad the necessary ones at signal boundaries).
Harmonic synthesis (Hmax=199, usemex=0)
100%   elapsed: 0:2                       
Compute: Adaptive Harmonic Model (aHM) using the Adaptive Iterative Refinment (AIR)
aHM-AIR analysis
         win_durnbper: 3
          win_ls_marg: 0.1000
               win_fn: @blackman
           use_f0time: 0
                 nbat: 1
                maxit: 24
                Kimin: 4
                Kimax: 12
                f0min: 50
                f0max: 2000
                  df0: 20
              f0_prec: 0.1000
             snr_prec: 0.1000
    do_final_ahm_step: 0
                debug: 1
               use_ls: 1
           fquasiharm: 1
               fmapin: {{1×2 cell}  {1×2 cell}}
              fmapout: {{1×2 cell}}

    Estimate main-lobe bandwidth w.r.t. winlen
    Adapt analysis instants to f0 curve with 1 analysis intants per period
    Compute window length and initial frequency limit
    Adaptation 1: 421/421 frames to update
100%   elapsed: 0:15                       
        max|df0|=40.1179 min(RCN)=-4.6112 max(dSNR)=20.2225
        421 frames: 64 finished, 20 converged, 310 improving (80 diverging)
    Adaptation 2: 421/421 frames to update
100%   elapsed: 0:15                       
        max|df0|=16.2495 min(RCN)=-4.6112 max(dSNR)=13.1506
        421 frames: 265 finished, 115 converged, 234 improving (115 diverging)
    Adaptation 3: 418/421 frames to update
100%   elapsed: 0:14                       
        max|df0|=5.9467 min(RCN)=-4.6112 max(dSNR)=2.0475
        421 frames: 377 finished, 276 converged, 158 improving (80 diverging)
    Adaptation 4: 386/421 frames to update
100%   elapsed: 0:13                       
        max|df0|=4.2097 min(RCN)=-4.6112 max(dSNR)=0.88535
        421 frames: 410 finished, 359 converged, 73 improving (39 diverging)
    Adaptation 5: 271/421 frames to update
100%   elapsed: 0:8                       
        max|df0|=1.2751 min(RCN)=-4.6112 max(dSNR)=0.53472
        421 frames: 418 finished, 391 converged, 42 improving (26 diverging)
    Adaptation 6: 185/421 frames to update
100%   elapsed: 0:5                       
        max|df0|=0.31835 min(RCN)=-4.6112 max(dSNR)=0.36579
        421 frames: 421 finished, 404 converged, 19 improving (16 diverging)
    Adaptation 7: 114/421 frames to update
100%   elapsed: 0:3                       
        max|df0|=0.20549 min(RCN)=-4.6112 max(dSNR)=0.23724
        421 frames: 421 finished, 412 converged, 13 improving (8 diverging)
    Adaptation 8: 76/421 frames to update
100%   elapsed: 0:2                       
        max|df0|=0.21939 min(RCN)=-4.6112 max(dSNR)=0.35106
        421 frames: 421 finished, 415 converged, 9 improving (2 diverging)
    Adaptation 9: 39/421 frames to update
100%   elapsed: 0:1                       
        max|df0|=0.33185 min(RCN)=-4.6112 max(dSNR)=0.3495
        421 frames: 421 finished, 415 converged, 7 improving (1 diverging)
    Adaptation 10: 29/421 frames to update
100%   elapsed: 0:0                       
        max|df0|=0.21056 min(RCN)=-4.6112 max(dSNR)=0.39967
        421 frames: 421 finished, 416 converged, 6 improving (1 diverging)
    Adaptation 11: 18/421 frames to update
100%   elapsed: 0:0                       
        max|df0|=0.17619 min(RCN)=-4.6112 max(dSNR)=0.18942
        421 frames: 421 finished, 418 converged, 3 improving (2 diverging)
    Adaptation 12: 16/421 frames to update
100%   elapsed: 0:0                       
        max|df0|=0.24116 min(RCN)=-4.6112 max(dSNR)=0.15671
        421 frames: 421 finished, 419 converged, 2 improving (1 diverging)
    Adaptation 13: 9/421 frames to update
100%   elapsed: 0:0                       
        max|df0|=0.20187 min(RCN)=-4.6112 max(dSNR)=0.19241
        421 frames: 421 finished, 420 converged, 3 improving (2 diverging)
    Adaptation 14: 10/421 frames to update
100%   elapsed: 0:0                       
        max|df0|=0.24158 min(RCN)=-4.6112 max(dSNR)=0.14723
        421 frames: 421 finished, 417 converged, 1 improving (1 diverging)
    Adaptation 15: 8/421 frames to update
100%   elapsed: 0:0                       
        max|df0|=0.24402 min(RCN)=-4.6112 max(dSNR)=0.16882
        421 frames: 421 finished, 418 converged, 2 improving (2 diverging)
    Adaptation 16: 10/421 frames to update
100%   elapsed: 0:0                       
        max|df0|=0.27398 min(RCN)=-4.6112 max(dSNR)=0.14378
        421 frames: 421 finished, 419 converged, 1 improving (1 diverging)
    Adaptation 17: 8/421 frames to update
100%   elapsed: 0:0                       
        max|df0|=0.23903 min(RCN)=-4.6112 max(dSNR)=0.14233
        421 frames: 421 finished, 419 converged, 1 improving (1 diverging)
    Adaptation 18: 8/421 frames to update
100%   elapsed: 0:0                       
        max|df0|=0.23706 min(RCN)=-4.6112 max(dSNR)=0.11171
        421 frames: 421 finished, 419 converged, 1 improving (1 diverging)
    Adaptation 19: 8/421 frames to update
100%   elapsed: 0:0                       
        max|df0|=0.18285 min(RCN)=-4.6112 max(dSNR)=0.096217
        421 frames: 421 finished, 419 converged, 0 improving (2 diverging)
    Adaptation 20: 6/421 frames to update
100%   elapsed: 0:0                       
        max|df0|=0.18507 min(RCN)=-4.6112 max(dSNR)=0.066158
        421 frames: 421 finished, 420 converged, 0 improving (1 diverging)
    Adaptation 21: 5/421 frames to update
100%   elapsed: 0:0                       
        max|df0|=0.17086 min(RCN)=-4.6112 max(dSNR)=0.014637
        421 frames: 421 finished, 420 converged, 0 improving (2 diverging)
    Adaptation 22: 6/421 frames to update
100%   elapsed: 0:0                       
        max|df0|=0.15951 min(RCN)=-4.6112 max(dSNR)=0.09216
        421 frames: 421 finished, 421 converged, 0 improving (1 diverging)
    Adaptation 23: 5/421 frames to update
100%   elapsed: 0:0                       
        max|df0|=0.15951 min(RCN)=-4.6112 max(dSNR)=0.0047299
        421 frames: 421 finished, 421 converged, 0 improving (1 diverging)
    Adaptation 24: 5/421 frames to update
100%   elapsed: 0:0                       
        max|df0|=0.15951 min(RCN)=-4.6112 max(dSNR)=0
        421 frames: 421 finished, 421 converged, 0 improving (1 diverging)
Compute the last step with uniform analysis instants
Sinusoidal Analysis
      win_durf0sync: 1
       win_durnbper: 3
            win_dur: 0.0300
             win_fn: @blackman
    win_dropoutside: 1
          fharmonic: 1
         fquasiharm: 0
           fadapted: 1
             use_ls: 1
        win_ls_marg: 0.1000
            normstr: 'sum(win)'
             dftlen: []
                osf: 2
    frames_keepspec: 0
            funique: 1
              resyn: 0
              debug: 1
             fmapin: {{1×2 cell}  {1×2 cell}}
            fmapout: {{1×2 cell}}

100%   elapsed: 0:8                       
    Some windows were outside of the signal. 6 frames dropped. (use opt.win_dropoutside=false if you want to keep all windows and zero-pad the necessary ones at signal boundaries).
Harmonic synthesis (Hmax=199, usemex=0)
100%   elapsed: 0:2                       
Warning: linkaxes is not implemented in Octave 
> In linkaxes (line 2)
  In HOWTO_sinusoidal (line 85)
  In HOWTO_all (line 5) 
Warning: linkaxes is not implemented in Octave 
> In linkaxes (line 2)
  In HOWTO_egg (line 88)
  In HOWTO_all (line 6) 
Warning: ind_max <= ind_min 
> In oq_egg (line 190)
  In oq_egg_sig (line 46)
  In HOWTO_egg (line 110)
  In HOWTO_all (line 6) 
Warning: ind_max <= ind_min 
> In oq_egg (line 190)
  In oq_egg_sig (line 46)
  In HOWTO_egg (line 110)
  In HOWTO_all (line 6) 
Warning: ind_max <= ind_min 
> In oq_egg (line 190)
  In oq_egg_sig (line 46)
  In HOWTO_egg (line 110)
  In HOWTO_all (line 6) 
Warning: ind_max <= ind_min 
> In oq_egg (line 190)
  In oq_egg_sig (line 46)
  In HOWTO_egg (line 110)
  In HOWTO_all (line 6) 
Warning: ind_max <= ind_min 
> In oq_egg (line 190)
  In oq_egg_sig (line 46)
  In HOWTO_egg (line 110)
  In HOWTO_all (line 6) 
Warning: linkaxes is not implemented in Octave 
> In linkaxes (line 2)
  In HOWTO_egg (line 159)
  In HOWTO_all (line 6) 
smooth - reducing N by 1
smooth - reducing N by 1
100%   elapsed: 0:1                       
Warning: linkaxes is not implemented in Octave 
> In linkaxes (line 2)
  In HOWTO_glottalsource (line 111)
  In HOWTO_all (line 7) 
Warning: linkaxes is not implemented in Octave 
> In linkaxes (line 2)
  In HOWTO_glottalsource (line 141)
  In HOWTO_all (line 7) 
Extracting Sadjadi's features
Extracting MFCCs
Extracting the new features
Warning: The file 'C:\Users\HLee\Documents\MATLAB\covarep\howtos\HOWTO_all.m' could not be cleared because it contains MATLAB code
that is currently executing. 
> In HOWTO_envelope (line 24)
  In HOWTO_all (line 9) 
Warning: The file 'C:\Users\HLee\Documents\MATLAB\covarep\howtos\HOWTO_envelope.m' could not be cleared because it contains MATLAB
code that is currently executing. 
> In HOWTO_envelope (line 24)
  In HOWTO_all (line 9) 
Warning: The file 'C:\Users\HLee\Documents\MATLAB\covarep\howtos\HOWTO_all.m' could not be cleared because it contains MATLAB code
that is currently executing. 
> In HOWTO_envelope (line 24)
  In HOWTO_all (line 9) 
Warning: The file 'C:\Users\HLee\Documents\MATLAB\covarep\howtos\HOWTO_envelope.m' could not be cleared because it contains MATLAB
code that is currently executing. 
> In HOWTO_envelope (line 24)
  In HOWTO_all (line 9) 
Warning: The file 'C:\Users\HLee\Documents\MATLAB\covarep\howtos\HOWTO_all.m' could not be cleared because it contains MATLAB code
that is currently executing. 
> In HOWTO_envelope (line 24)
  In HOWTO_all (line 9) 
Warning: The file 'C:\Users\HLee\Documents\MATLAB\covarep\howtos\HOWTO_envelope.m' could not be cleared because it contains MATLAB
code that is currently executing. 
> In HOWTO_envelope (line 24)
  In HOWTO_all (line 9) 
Sample rate is bigger than 16kHz. Audio is resampled.
Estimate spectral peaks and spectra at regular intervals
Sinusoidal Analysis
      win_durf0sync: 1
       win_durnbper: 3
            win_dur: 0.0300
             win_fn: @blackman
    win_dropoutside: 1
          fharmonic: 0
         fquasiharm: 0
           fadapted: 0
             use_ls: 0
        win_ls_marg: 0.1000
            normstr: 'sum(win)'
             dftlen: 4096
                osf: 2
    frames_keepspec: 1
            funique: 1
              resyn: 0
              debug: 1
             fmapin: {{1×2 cell}  {1×2 cell}}
            fmapout: {{1×2 cell}}

100%   elapsed: 0:0                       
    Some windows were outside of the signal. 5 frames dropped. (use opt.win_dropoutside=false if you want to keep all windows and zero-pad the necessary ones at signal boundaries).
Compute Discrete All-Pole (DAP) envelope
100%   elapsed: 0:0                       
Compute the so-called "True-Envelope"
100%   elapsed: 0:2                       
Compute WLP, SWLP, and XLP (LP variants), FIHR and FIHRZP
100%   elapsed: 0:2                       
Discrete-Cepstral-Envelope Multi-Frame-Analysis (DCE-MFA)
100%   elapsed: 0:5                       
Compute the Relative Phase Shift and Phase Distortion
Sinusoidal Analysis
      win_durf0sync: 1
       win_durnbper: 3
            win_dur: 0.0300
             win_fn: @blackman
    win_dropoutside: 1
          fharmonic: 1
         fquasiharm: 0
           fadapted: 0
             use_ls: 0
        win_ls_marg: 0.1000
            normstr: 'sum(win)'
             dftlen: []
                osf: 2
    frames_keepspec: 0
            funique: 1
              resyn: 0
              debug: 1
             fmapin: {{1×2 cell}  {1×2 cell}}
            fmapout: {{1×2 cell}}

100%   elapsed: 0:0                       
    Some windows were outside of the signal. 5 frames dropped. (use opt.win_dropoutside=false if you want to keep all windows and zero-pad the necessary ones at signal boundaries).
Warning: linkaxes is not implemented in Octave 
> In linkaxes (line 2)
  In HOWTO_envelope (line 236)
  In HOWTO_all (line 9) 
Warning: The file 'C:\Users\HLee\Documents\MATLAB\covarep\howtos\HOWTO_all.m' could not be cleared because it contains MATLAB code
that is currently executing. 
> In HOWTO_formant (line 26)
  In HOWTO_all (line 10) 
Warning: The file 'C:\Users\HLee\Documents\MATLAB\covarep\howtos\HOWTO_formant.m' could not be cleared because it contains MATLAB
code that is currently executing. 
> In HOWTO_formant (line 26)
  In HOWTO_all (line 10) 
Warning: The file 'C:\Users\HLee\Documents\MATLAB\covarep\howtos\HOWTO_all.m' could not be cleared because it contains MATLAB code
that is currently executing. 
> In HOWTO_formant (line 26)
  In HOWTO_all (line 10) 
Warning: The file 'C:\Users\HLee\Documents\MATLAB\covarep\howtos\HOWTO_formant.m' could not be cleared because it contains MATLAB
code that is currently executing. 
> In HOWTO_formant (line 26)
  In HOWTO_all (line 10) 
Warning: The file 'C:\Users\HLee\Documents\MATLAB\covarep\howtos\HOWTO_all.m' could not be cleared because it contains MATLAB code
that is currently executing. 
> In HOWTO_formant (line 26)
  In HOWTO_all (line 10) 
Warning: The file 'C:\Users\HLee\Documents\MATLAB\covarep\howtos\HOWTO_formant.m' could not be cleared because it contains MATLAB
code that is currently executing. 
> In HOWTO_formant (line 26)
  In HOWTO_all (line 10) 
Warning: linkaxes is not implemented in Octave 
> In linkaxes (line 2)
  In HOWTO_formant (line 52)
  In HOWTO_all (line 10) 
Warning: The file 'C:\Users\HLee\Documents\MATLAB\covarep\howtos\HOWTO_all.m' could not be cleared because it contains MATLAB code
that is currently executing. 
> In HOWTO_hmpd (line 23)
  In HOWTO_all (line 11) 
Warning: The file 'C:\Users\HLee\Documents\MATLAB\covarep\howtos\HOWTO_hmpd.m' could not be cleared because it contains MATLAB
code that is currently executing. 
> In HOWTO_hmpd (line 23)
  In HOWTO_all (line 11) 
Warning: The file 'C:\Users\HLee\Documents\MATLAB\covarep\howtos\HOWTO_all.m' could not be cleared because it contains MATLAB code
that is currently executing. 
> In HOWTO_hmpd (line 23)
  In HOWTO_all (line 11) 
Warning: The file 'C:\Users\HLee\Documents\MATLAB\covarep\howtos\HOWTO_hmpd.m' could not be cleared because it contains MATLAB
code that is currently executing. 
> In HOWTO_hmpd (line 23)
  In HOWTO_all (line 11) 
Warning: The file 'C:\Users\HLee\Documents\MATLAB\covarep\howtos\HOWTO_all.m' could not be cleared because it contains MATLAB code
that is currently executing. 
> In HOWTO_hmpd (line 23)
  In HOWTO_all (line 11) 
Warning: The file 'C:\Users\HLee\Documents\MATLAB\covarep\howtos\HOWTO_hmpd.m' could not be cleared because it contains MATLAB
code that is currently executing. 
> In HOWTO_hmpd (line 23)
  In HOWTO_all (line 11) 
HMPD Vocoder: Harmonic analysis ...
    No f0 provided in arguments, estimate it using SRH ...
Sample rate is bigger than 16kHz. Audio is resampled.
    Estimation of sinusoidal parameters ...
    Adapt analysis instants to f0 curve with 4 analysis intants per period
HMPD Vocoder: Features computation ...
    Estimate amplitude envelope ...
100%   elapsed: 0:0                       
    Estimate phase envelope ...
    Compute phase statistics ...
    Compress features ...
    Resample features with uniform sampling ...
HMPD Vocoder: Synthesis ...
wrappednormrnd.m: Pre-compute the cumulative distribution function once for all ... done.
    HM synthesis (214 harmonics)
HMPD Vocoder: Synthesis ...
    HM synthesis (214 harmonics)
Warning: linkaxes is not implemented in Octave 
> In linkaxes (line 2)
  In HOWTO_hmpd (line 101)
  In HOWTO_all (line 11) `
