### ISSUE TITLE
First use information

### ISSUE THREAD

**Issue by rikop85** [covarep/covarep#94]
I'm having some problems using COVAREX for the first time. I'm not a expert user of Matlab, so my difficulties may only be due to this. So:

1) I have installed the covarep_lib_installer.exe. It is now necessary to install the library on Matlab? I tried to add it through the add path box, but it did not work. I also tried to install and launch the covarep_standalone, bi it returns me thsi error "Ann error occured while trying to determine whether "covarep future extraction  " is a function name. What are the step necessary to use the covarep functions in matlab?
2) What  other matlab toolbox are necessary ?tsa, optimization, signal and voicebox?
3) It is necessary to have at least Matlab 2015b version?

Thanks fo answering.

**Comment by gillesdegottex** [comment]
Hi,

1. If you're using the Matlab interface (GUI or command line), you don't need to install covarep_lib_installer.exe. This executable is to run a standalone version of features extraction (as far as I remember (I'm not the maintainer of this)).

2. You might need tsa, optimisation and signal toolbox. There is a voicebox toolbox already included in COVAREP package.

3. Unfortunately, it is hard to know which Matlab version you need. It all depends on which functions of COVAREP you will be using. Some of them are compatible with very old Matlab versions, some others need more recent version and some of them might start to be incompatible with very new versions. Sorry, I can't help on this. Just run what you want ... and see !

Cheers,

**Comment by gillesdegottex** [comment]
No news, can be re-oppened if necessary.
