### ISSUE TITLE
Covarep standalone_installer won't open

### ISSUE THREAD

**Issue by gwicks56** [covarep/covarep#95]
Not sure if I am doing something wrong. I am running Windows 10, and downloaded the covarep_standalone_installer.exe.

I have matlab installed (2016b), and the installation proceeded fine. I now have a folder called covarep in my program files directory, and in order to run it i double clicked the covarep.exe file.
(c:\ProgramFiles(x86)/Covarep/application/covarep.exe)

The splash screen shows for about 5-10 seconds, then closes, with the application not showing in my list of running programs.

Just wondering if I am doing something incorrectly, or if anybody can point me towards a tutorial.

Thanks, any help appreciated.

**Comment by gillesdegottex** [comment]
COVAREP is a Matlab toolbox which is first supposed to be used in Matlab (with GUI or command line).
The installer you just ran installs a covarep console command that allows you to extract features from waveforms (features that can also be extracted within Matlab).
Could you tell me what you're looking for exactly?

**Comment by gwicks56** [comment]
thanks @gillesdegottex ..... is there an online manual or tutorial you could point me towards? I have not been able to find a list of commands etc in Matlab

**Comment by gillesdegottex** [comment]
For the Matlab commands, you can have a look at the list of functions here:
http://covarep.github.io/covarep/contributions.html
Then you have to dig into the matlab files to see the details. The doc is into the code.

**Comment by gwicks56** [comment]
OK, thanks, I appreciate you taking the time to answer.
