### ISSUE TITLE
Error running COVAREP_feature_extraction

### ISSUE THREAD

**Issue by michellemorales** [covarep/covarep#96]
I am getting an error with `COVAREP_feature_extraction` when I try to extract features for a short clip. I get the following error:

```
> In COVAREP_feature_extraction (line 218)
Analysing file: word_4
100%   elapsed: 0:0                       
Warning: An error occurred while analysing word_6: Error using filtfilt>getCoeffsAndInitialConditions (line 182)
Data length must be larger than 72 samples.
```
The script works fine for longer audio files. Any suggestions on how to handle the error? Here are the details of the audio file..

```
Input File     : 'wavs/word_4.wav'
Channels       : 1
Sample Rate    : 16000
Precision      : 16-bit
Duration       : 00:00:00.39 = 6240 samples ~ 29.25 CDDA sectors
File Size      : 12.5k
Bit Rate       : 257k
Sample Encoding: 16-bit Signed Integer PCM
```

Thanks in advance!

**Comment by gillesdegottex** [comment]
Hi,
I don't see which feature extraction breaks on this, but I wouldn't be surprise it does on such short audio files (0.4s right?)

If you can skip this file, it might be the easiest "workaround". Otherwise, you can try padding it with pseudo zero values (e.g. eps*rand(1,N) )

G

**Comment by gillesdegottex** [comment]
No news, closing. Can be re-opened later if need be.

**Comment by BrankaZei** [comment]
Please unsubscribe me

bzp
